/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: client_server.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "client_server.pb-c.h"
void   header__message__init
                     (HeaderMessage         *message)
{
  static const HeaderMessage init_value = HEADER__MESSAGE__INIT;
  *message = init_value;
}
size_t header__message__get_packed_size
                     (const HeaderMessage *message)
{
  assert(message->base.descriptor == &header__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__message__pack
                     (const HeaderMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__message__pack_to_buffer
                     (const HeaderMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HeaderMessage *
       header__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HeaderMessage *)
     protobuf_c_message_unpack (&header__message__descriptor,
                                allocator, len, data);
}
void   header__message__free_unpacked
                     (HeaderMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &header__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__display__message__init
                     (ProtoDisplayMessage         *message)
{
  static const ProtoDisplayMessage init_value = PROTO__DISPLAY__MESSAGE__INIT;
  *message = init_value;
}
size_t proto__display__message__get_packed_size
                     (const ProtoDisplayMessage *message)
{
  assert(message->base.descriptor == &proto__display__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__display__message__pack
                     (const ProtoDisplayMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__display__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__display__message__pack_to_buffer
                     (const ProtoDisplayMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__display__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoDisplayMessage *
       proto__display__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoDisplayMessage *)
     protobuf_c_message_unpack (&proto__display__message__descriptor,
                                allocator, len, data);
}
void   proto__display__message__free_unpacked
                     (ProtoDisplayMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__display__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roach__connect__req__init
                     (RoachConnectReq         *message)
{
  static const RoachConnectReq init_value = ROACH__CONNECT__REQ__INIT;
  *message = init_value;
}
size_t roach__connect__req__get_packed_size
                     (const RoachConnectReq *message)
{
  assert(message->base.descriptor == &roach__connect__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roach__connect__req__pack
                     (const RoachConnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roach__connect__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roach__connect__req__pack_to_buffer
                     (const RoachConnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roach__connect__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachConnectReq *
       roach__connect__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachConnectReq *)
     protobuf_c_message_unpack (&roach__connect__req__descriptor,
                                allocator, len, data);
}
void   roach__connect__req__free_unpacked
                     (RoachConnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roach__connect__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasp__connect__req__init
                     (WaspConnectReq         *message)
{
  static const WaspConnectReq init_value = WASP__CONNECT__REQ__INIT;
  *message = init_value;
}
size_t wasp__connect__req__get_packed_size
                     (const WaspConnectReq *message)
{
  assert(message->base.descriptor == &wasp__connect__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasp__connect__req__pack
                     (const WaspConnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasp__connect__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasp__connect__req__pack_to_buffer
                     (const WaspConnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasp__connect__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspConnectReq *
       wasp__connect__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspConnectReq *)
     protobuf_c_message_unpack (&wasp__connect__req__descriptor,
                                allocator, len, data);
}
void   wasp__connect__req__free_unpacked
                     (WaspConnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasp__connect__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bot__connect__resp__init
                     (BotConnectResp         *message)
{
  static const BotConnectResp init_value = BOT__CONNECT__RESP__INIT;
  *message = init_value;
}
size_t bot__connect__resp__get_packed_size
                     (const BotConnectResp *message)
{
  assert(message->base.descriptor == &bot__connect__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot__connect__resp__pack
                     (const BotConnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot__connect__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot__connect__resp__pack_to_buffer
                     (const BotConnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot__connect__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotConnectResp *
       bot__connect__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotConnectResp *)
     protobuf_c_message_unpack (&bot__connect__resp__descriptor,
                                allocator, len, data);
}
void   bot__connect__resp__free_unpacked
                     (BotConnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot__connect__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bot__movement__req__init
                     (BotMovementReq         *message)
{
  static const BotMovementReq init_value = BOT__MOVEMENT__REQ__INIT;
  *message = init_value;
}
size_t bot__movement__req__get_packed_size
                     (const BotMovementReq *message)
{
  assert(message->base.descriptor == &bot__movement__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot__movement__req__pack
                     (const BotMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot__movement__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot__movement__req__pack_to_buffer
                     (const BotMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot__movement__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotMovementReq *
       bot__movement__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotMovementReq *)
     protobuf_c_message_unpack (&bot__movement__req__descriptor,
                                allocator, len, data);
}
void   bot__movement__req__free_unpacked
                     (BotMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot__movement__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bot__movement__resp__init
                     (BotMovementResp         *message)
{
  static const BotMovementResp init_value = BOT__MOVEMENT__RESP__INIT;
  *message = init_value;
}
size_t bot__movement__resp__get_packed_size
                     (const BotMovementResp *message)
{
  assert(message->base.descriptor == &bot__movement__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot__movement__resp__pack
                     (const BotMovementResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot__movement__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot__movement__resp__pack_to_buffer
                     (const BotMovementResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot__movement__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotMovementResp *
       bot__movement__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotMovementResp *)
     protobuf_c_message_unpack (&bot__movement__resp__descriptor,
                                allocator, len, data);
}
void   bot__movement__resp__free_unpacked
                     (BotMovementResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot__movement__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bot__disconnect__req__init
                     (BotDisconnectReq         *message)
{
  static const BotDisconnectReq init_value = BOT__DISCONNECT__REQ__INIT;
  *message = init_value;
}
size_t bot__disconnect__req__get_packed_size
                     (const BotDisconnectReq *message)
{
  assert(message->base.descriptor == &bot__disconnect__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot__disconnect__req__pack
                     (const BotDisconnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot__disconnect__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot__disconnect__req__pack_to_buffer
                     (const BotDisconnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot__disconnect__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotDisconnectReq *
       bot__disconnect__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotDisconnectReq *)
     protobuf_c_message_unpack (&bot__disconnect__req__descriptor,
                                allocator, len, data);
}
void   bot__disconnect__req__free_unpacked
                     (BotDisconnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot__disconnect__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bot__disconnect__resp__init
                     (BotDisconnectResp         *message)
{
  static const BotDisconnectResp init_value = BOT__DISCONNECT__RESP__INIT;
  *message = init_value;
}
size_t bot__disconnect__resp__get_packed_size
                     (const BotDisconnectResp *message)
{
  assert(message->base.descriptor == &bot__disconnect__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bot__disconnect__resp__pack
                     (const BotDisconnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bot__disconnect__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bot__disconnect__resp__pack_to_buffer
                     (const BotDisconnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bot__disconnect__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BotDisconnectResp *
       bot__disconnect__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BotDisconnectResp *)
     protobuf_c_message_unpack (&bot__disconnect__resp__descriptor,
                                allocator, len, data);
}
void   bot__disconnect__resp__free_unpacked
                     (BotDisconnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bot__disconnect__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__connect__req__init
                     (LizardConnectReq         *message)
{
  static const LizardConnectReq init_value = LIZARD__CONNECT__REQ__INIT;
  *message = init_value;
}
size_t lizard__connect__req__get_packed_size
                     (const LizardConnectReq *message)
{
  assert(message->base.descriptor == &lizard__connect__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__connect__req__pack
                     (const LizardConnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__connect__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__connect__req__pack_to_buffer
                     (const LizardConnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__connect__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardConnectReq *
       lizard__connect__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardConnectReq *)
     protobuf_c_message_unpack (&lizard__connect__req__descriptor,
                                allocator, len, data);
}
void   lizard__connect__req__free_unpacked
                     (LizardConnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__connect__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__connect__resp__init
                     (LizardConnectResp         *message)
{
  static const LizardConnectResp init_value = LIZARD__CONNECT__RESP__INIT;
  *message = init_value;
}
size_t lizard__connect__resp__get_packed_size
                     (const LizardConnectResp *message)
{
  assert(message->base.descriptor == &lizard__connect__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__connect__resp__pack
                     (const LizardConnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__connect__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__connect__resp__pack_to_buffer
                     (const LizardConnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__connect__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardConnectResp *
       lizard__connect__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardConnectResp *)
     protobuf_c_message_unpack (&lizard__connect__resp__descriptor,
                                allocator, len, data);
}
void   lizard__connect__resp__free_unpacked
                     (LizardConnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__connect__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__movement__req__init
                     (LizardMovementReq         *message)
{
  static const LizardMovementReq init_value = LIZARD__MOVEMENT__REQ__INIT;
  *message = init_value;
}
size_t lizard__movement__req__get_packed_size
                     (const LizardMovementReq *message)
{
  assert(message->base.descriptor == &lizard__movement__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__movement__req__pack
                     (const LizardMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__movement__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__movement__req__pack_to_buffer
                     (const LizardMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__movement__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMovementReq *
       lizard__movement__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMovementReq *)
     protobuf_c_message_unpack (&lizard__movement__req__descriptor,
                                allocator, len, data);
}
void   lizard__movement__req__free_unpacked
                     (LizardMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__movement__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__movement__resp__init
                     (LizardMovementResp         *message)
{
  static const LizardMovementResp init_value = LIZARD__MOVEMENT__RESP__INIT;
  *message = init_value;
}
size_t lizard__movement__resp__get_packed_size
                     (const LizardMovementResp *message)
{
  assert(message->base.descriptor == &lizard__movement__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__movement__resp__pack
                     (const LizardMovementResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__movement__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__movement__resp__pack_to_buffer
                     (const LizardMovementResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__movement__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMovementResp *
       lizard__movement__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMovementResp *)
     protobuf_c_message_unpack (&lizard__movement__resp__descriptor,
                                allocator, len, data);
}
void   lizard__movement__resp__free_unpacked
                     (LizardMovementResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__movement__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__disconnect__req__init
                     (LizardDisconnectReq         *message)
{
  static const LizardDisconnectReq init_value = LIZARD__DISCONNECT__REQ__INIT;
  *message = init_value;
}
size_t lizard__disconnect__req__get_packed_size
                     (const LizardDisconnectReq *message)
{
  assert(message->base.descriptor == &lizard__disconnect__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__disconnect__req__pack
                     (const LizardDisconnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__disconnect__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__disconnect__req__pack_to_buffer
                     (const LizardDisconnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__disconnect__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardDisconnectReq *
       lizard__disconnect__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardDisconnectReq *)
     protobuf_c_message_unpack (&lizard__disconnect__req__descriptor,
                                allocator, len, data);
}
void   lizard__disconnect__req__free_unpacked
                     (LizardDisconnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__disconnect__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__disconnect__resp__init
                     (LizardDisconnectResp         *message)
{
  static const LizardDisconnectResp init_value = LIZARD__DISCONNECT__RESP__INIT;
  *message = init_value;
}
size_t lizard__disconnect__resp__get_packed_size
                     (const LizardDisconnectResp *message)
{
  assert(message->base.descriptor == &lizard__disconnect__resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__disconnect__resp__pack
                     (const LizardDisconnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__disconnect__resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__disconnect__resp__pack_to_buffer
                     (const LizardDisconnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__disconnect__resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardDisconnectResp *
       lizard__disconnect__resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardDisconnectResp *)
     protobuf_c_message_unpack (&lizard__disconnect__resp__descriptor,
                                allocator, len, data);
}
void   lizard__disconnect__resp__free_unpacked
                     (LizardDisconnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__disconnect__resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor header__message__field_descriptors[2] =
{
  {
    "client_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(HeaderMessage, client_type),
    &client_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(HeaderMessage, msg_type),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__message__field_indices_by_name[] = {
  0,   /* field[0] = client_type */
  1,   /* field[1] = msg_type */
};
static const ProtobufCIntRange header__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor header__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header_Message",
  "HeaderMessage",
  "HeaderMessage",
  "",
  sizeof(HeaderMessage),
  2,
  header__message__field_descriptors,
  header__message__field_indices_by_name,
  1,  header__message__number_ranges,
  (ProtobufCMessageInit) header__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__display__message__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtoDisplayMessage, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoDisplayMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoDisplayMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__display__message__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = pos_x */
  2,   /* field[2] = pos_y */
};
static const ProtobufCIntRange proto__display__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__display__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Display_Message",
  "ProtoDisplayMessage",
  "ProtoDisplayMessage",
  "",
  sizeof(ProtoDisplayMessage),
  3,
  proto__display__message__field_descriptors,
  proto__display__message__field_indices_by_name,
  1,  proto__display__message__number_ranges,
  (ProtobufCMessageInit) proto__display__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roach__connect__req__field_descriptors[1] =
{
  {
    "roach_digit",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RoachConnectReq, n_roach_digit),
    offsetof(RoachConnectReq, roach_digit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roach__connect__req__field_indices_by_name[] = {
  0,   /* field[0] = roach_digit */
};
static const ProtobufCIntRange roach__connect__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor roach__connect__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Roach_Connect_Req",
  "RoachConnectReq",
  "RoachConnectReq",
  "",
  sizeof(RoachConnectReq),
  1,
  roach__connect__req__field_descriptors,
  roach__connect__req__field_indices_by_name,
  1,  roach__connect__req__number_ranges,
  (ProtobufCMessageInit) roach__connect__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasp__connect__req__field_descriptors[1] =
{
  {
    "num_wasps",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WaspConnectReq, num_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasp__connect__req__field_indices_by_name[] = {
  0,   /* field[0] = num_wasps */
};
static const ProtobufCIntRange wasp__connect__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wasp__connect__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Wasp_Connect_Req",
  "WaspConnectReq",
  "WaspConnectReq",
  "",
  sizeof(WaspConnectReq),
  1,
  wasp__connect__req__field_descriptors,
  wasp__connect__req__field_indices_by_name,
  1,  wasp__connect__req__number_ranges,
  (ProtobufCMessageInit) wasp__connect__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bot__connect__resp__field_descriptors[3] =
{
  {
    "bot_id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BotConnectResp, n_bot_id),
    offsetof(BotConnectResp, bot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(BotConnectResp, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BotConnectResp, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot__connect__resp__field_indices_by_name[] = {
  0,   /* field[0] = bot_id */
  2,   /* field[2] = client_id */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange bot__connect__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bot__connect__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bot_Connect_Resp",
  "BotConnectResp",
  "BotConnectResp",
  "",
  sizeof(BotConnectResp),
  3,
  bot__connect__resp__field_descriptors,
  bot__connect__resp__field_indices_by_name,
  1,  bot__connect__resp__number_ranges,
  (ProtobufCMessageInit) bot__connect__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bot__movement__req__field_descriptors[4] =
{
  {
    "bot_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BotMovementReq, bot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(BotMovementReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotMovementReq, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BotMovementReq, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot__movement__req__field_indices_by_name[] = {
  0,   /* field[0] = bot_id */
  3,   /* field[3] = client_id */
  2,   /* field[2] = direction */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange bot__movement__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor bot__movement__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bot_Movement_Req",
  "BotMovementReq",
  "BotMovementReq",
  "",
  sizeof(BotMovementReq),
  4,
  bot__movement__req__field_descriptors,
  bot__movement__req__field_indices_by_name,
  1,  bot__movement__req__number_ranges,
  (ProtobufCMessageInit) bot__movement__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bot__movement__resp__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotMovementResp, resp),
    &response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot__movement__resp__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange bot__movement__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bot__movement__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bot_Movement_Resp",
  "BotMovementResp",
  "BotMovementResp",
  "",
  sizeof(BotMovementResp),
  1,
  bot__movement__resp__field_descriptors,
  bot__movement__resp__field_indices_by_name,
  1,  bot__movement__resp__number_ranges,
  (ProtobufCMessageInit) bot__movement__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bot__disconnect__req__field_descriptors[2] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BotDisconnectReq, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(BotDisconnectReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot__disconnect__req__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange bot__disconnect__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bot__disconnect__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bot_Disconnect_Req",
  "BotDisconnectReq",
  "BotDisconnectReq",
  "",
  sizeof(BotDisconnectReq),
  2,
  bot__disconnect__req__field_descriptors,
  bot__disconnect__req__field_indices_by_name,
  1,  bot__disconnect__req__number_ranges,
  (ProtobufCMessageInit) bot__disconnect__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bot__disconnect__resp__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BotDisconnectResp, resp),
    &response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bot__disconnect__resp__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange bot__disconnect__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bot__disconnect__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bot_Disconnect_Resp",
  "BotDisconnectResp",
  "BotDisconnectResp",
  "",
  sizeof(BotDisconnectResp),
  1,
  bot__disconnect__resp__field_descriptors,
  bot__disconnect__resp__field_indices_by_name,
  1,  bot__disconnect__resp__number_ranges,
  (ProtobufCMessageInit) bot__disconnect__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__connect__req__field_descriptors[1] =
{
  {
    "null",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(LizardConnectReq, has_null),
    offsetof(LizardConnectReq, null),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__connect__req__field_indices_by_name[] = {
  0,   /* field[0] = null */
};
static const ProtobufCIntRange lizard__connect__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lizard__connect__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Connect_Req",
  "LizardConnectReq",
  "LizardConnectReq",
  "",
  sizeof(LizardConnectReq),
  1,
  lizard__connect__req__field_descriptors,
  lizard__connect__req__field_indices_by_name,
  1,  lizard__connect__req__number_ranges,
  (ProtobufCMessageInit) lizard__connect__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__connect__resp__field_descriptors[2] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardConnectResp, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LizardConnectResp, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__connect__resp__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange lizard__connect__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lizard__connect__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Connect_Resp",
  "LizardConnectResp",
  "LizardConnectResp",
  "",
  sizeof(LizardConnectResp),
  2,
  lizard__connect__resp__field_descriptors,
  lizard__connect__resp__field_indices_by_name,
  1,  lizard__connect__resp__number_ranges,
  (ProtobufCMessageInit) lizard__connect__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__movement__req__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__movement__req__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  2,   /* field[2] = direction */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange lizard__movement__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard__movement__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Movement_Req",
  "LizardMovementReq",
  "LizardMovementReq",
  "",
  sizeof(LizardMovementReq),
  3,
  lizard__movement__req__field_descriptors,
  lizard__movement__req__field_indices_by_name,
  1,  lizard__movement__req__number_ranges,
  (ProtobufCMessageInit) lizard__movement__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__movement__resp__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardMovementResp, resp),
    &response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__movement__resp__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange lizard__movement__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lizard__movement__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Movement_Resp",
  "LizardMovementResp",
  "LizardMovementResp",
  "",
  sizeof(LizardMovementResp),
  1,
  lizard__movement__resp__field_descriptors,
  lizard__movement__resp__field_indices_by_name,
  1,  lizard__movement__resp__number_ranges,
  (ProtobufCMessageInit) lizard__movement__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__disconnect__req__field_descriptors[2] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectReq, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__disconnect__req__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange lizard__disconnect__req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lizard__disconnect__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Disconnect_Req",
  "LizardDisconnectReq",
  "LizardDisconnectReq",
  "",
  sizeof(LizardDisconnectReq),
  2,
  lizard__disconnect__req__field_descriptors,
  lizard__disconnect__req__field_indices_by_name,
  1,  lizard__disconnect__req__number_ranges,
  (ProtobufCMessageInit) lizard__disconnect__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__disconnect__resp__field_descriptors[1] =
{
  {
    "score",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectResp, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__disconnect__resp__field_indices_by_name[] = {
  0,   /* field[0] = score */
};
static const ProtobufCIntRange lizard__disconnect__resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lizard__disconnect__resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard_Disconnect_Resp",
  "LizardDisconnectResp",
  "LizardDisconnectResp",
  "",
  sizeof(LizardDisconnectResp),
  1,
  lizard__disconnect__resp__field_descriptors,
  lizard__disconnect__resp__field_indices_by_name,
  1,  lizard__disconnect__resp__number_ranges,
  (ProtobufCMessageInit) lizard__disconnect__resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[4] =
{
  { "UP", "DIRECTION__UP", 0 },
  { "DOWN", "DIRECTION__DOWN", 1 },
  { "LEFT", "DIRECTION__LEFT", 2 },
  { "RIGHT", "DIRECTION__RIGHT", 3 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  4,
  direction__enum_values_by_number,
  4,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[4] =
{
  { "CONNECT", "MESSAGE_TYPE__CONNECT", 0 },
  { "MOVEMENT", "MESSAGE_TYPE__MOVEMENT", 1 },
  { "DISCONNECT", "MESSAGE_TYPE__DISCONNECT", 2 },
  { "REQUEST", "MESSAGE_TYPE__REQUEST", 3 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[4] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 2 },
  { "MOVEMENT", 1 },
  { "REQUEST", 3 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  4,
  message_type__enum_values_by_number,
  4,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_type__enum_values_by_number[3] =
{
  { "LIZARD", "CLIENT_TYPE__LIZARD", 0 },
  { "ROACH", "CLIENT_TYPE__ROACH", 1 },
  { "WASP", "CLIENT_TYPE__WASP", 2 },
};
static const ProtobufCIntRange client_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex client_type__enum_values_by_name[3] =
{
  { "LIZARD", 0 },
  { "ROACH", 1 },
  { "WASP", 2 },
};
const ProtobufCEnumDescriptor client_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientType",
  "ClientType",
  "ClientType",
  "",
  3,
  client_type__enum_values_by_number,
  3,
  client_type__enum_values_by_name,
  1,
  client_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue response__enum_values_by_number[4] =
{
  { "SUCCESS", "RESPONSE__SUCCESS", 0 },
  { "NOTHING", "RESPONSE__NOTHING", 1 },
  { "FAILURE", "RESPONSE__FAILURE", 2 },
  { "TIMEOUT", "RESPONSE__TIMEOUT", 3 },
};
static const ProtobufCIntRange response__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex response__enum_values_by_name[4] =
{
  { "FAILURE", 2 },
  { "NOTHING", 1 },
  { "SUCCESS", 0 },
  { "TIMEOUT", 3 },
};
const ProtobufCEnumDescriptor response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  4,
  response__enum_values_by_number,
  4,
  response__enum_values_by_name,
  1,
  response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
