all:
	make -C Display-app all
	make -C Lizard-client all
	make -C lizardsNroach all
	make -C Roaches-client all

clean:
	make -C Display-app clean
	make -C Lizard-client clean
	make -C lizardsNroach clean
	make -C Roaches-client clean

