all:
	make --no-print-directory -C src all
	make --no-print-directory -C Lizard-client all
	make --no-print-directory -C lizardsNroach all
	make --no-print-directory -C Roaches-client all
	make --no-print-directory -C Wasps-client all

clean:
	make --no-print-directory -C lizardsNroach clean
	make --no-print-directory -C Lizard-client clean
	make --no-print-directory -C Roaches-client clean
	make --no-print-directory -C Wasps-client clean
	make --no-print-directory -C src clean
